import type { Metadata } from 'next'
import React from 'react'
import { Quicksand } from 'next/font/google'
import '@/app/globals.css'

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import 'primereact/resources/themes/lara-light-blue/theme.css'

import Navbar from '@/components/Navbar/Navbar'
import { NextIntlClientProvider, useMessages } from 'next-intl'

const quicksand = Quicksand({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Naochizuki',
  description: 'Generated by create next app',
  icons: [{ rel: "icon", url:'../favicon.ico' }]
}

type Props = {
  children: React.ReactNode
  params: {
    locale: 'id' | 'en' | 'jp'
  }
}

const RootLayout: React.FC<Props> = ({
  children,
  params: { locale }
}) => {
  const messages = useMessages()

  return (
    <html lang={ locale } suppressHydrationWarning>
      <body className={quicksand.className}>
        <NextIntlClientProvider messages={ messages }>
          <Navbar font={ quicksand.className } />
          <div className='px-2'>
           {children}
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}

export default RootLayout
